language: php

os:
  - linux

php:
  - 5.4
  - 5.5
  - 5.6

notifications:
  email: wukezhan@gmail.com

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

before_script:
    - ./tests/travis/compile.sh

script:
    - ./tests/travis/run-tests.sh
